<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-MCF4SQC" failures="2" tests="2" name="Default test(failed)(failed)" time="0.029" errors="0" timestamp="17 May 2023 03:14:41 GMT">
  <testcase classname="com.testNGChallanges.FailedTestCases" name="getTestOne" time="0.009">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.testNGChallanges.FailedTestCases.getTestOne(FailedTestCases.java:9)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- getTestOne -->
  <testcase classname="com.testNGChallanges.FailedTestCases" name="getTestFive" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.testNGChallanges.FailedTestCases.getTestFive(FailedTestCases.java:30)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- getTestFive -->
  <testcase classname="com.testNGChallanges.FailedTestCases" name="getTestFour" time="0.0">
    <ignored/>
  </testcase> <!-- getTestFour -->
  <testcase classname="com.testNGChallanges.FailedTestCases" name="getTestThree" time="0.0">
    <ignored/>
  </testcase> <!-- getTestThree -->
  <testcase classname="com.testNGChallanges.FailedTestCases" name="getTestTwo" time="0.0">
    <ignored/>
  </testcase> <!-- getTestTwo -->
</testsuite> <!-- Default test(failed)(failed) -->
